name: git_pilot_presentation
description: Presentation layer for Git Pilot.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  git_pilot_domain:
    path: ../domain
  orient_ui: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
